name: CI-UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ui:
    runs-on: ubuntu-latest

    # your repo root is the frontend, so no subfolder here
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # IMPORTANT: path relative to repo root
          cache-dependency-path: package-lock.json

      - name: Debug tree
        run: |
          pwd
          ls -la
          test -f package.json && echo "Found package.json"
          test -f package-lock.json && echo "Found package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        env:
          CI: true
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build

      - name: Upload UI artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          # Vite outputs dist/ (CRA uses build/). Include both, ignore if missing.
          path: |
            dist
            build
          if-no-files-found: ignore
